### ISSUE TITLE
Error: file.warn is not a function

### ISSUE THREAD

**Issue by franciscodua** [vhf/remark-lint-alphabetize-lists#3]
Hi
This remark-lint plugin doesn't seem to be up-to-date with the latest vFile. The new versions of vFile do not have a `VFile.warn` method.
If I understood correctly, `warn` should now be replaced with `message`.

When this plugin finds an issue it outputs an error saying `file.warn is not a function`, instead of outputting an issue with the message and line number.

This means that the vFile version cannot be bumped (neither can projects that depend on it, e.g., unified-engine) if projects are using this plugin.

Thanks

**Comment by vhf** [comment]
@franciscodua Thanks for the issue! Would you have time to submit a PR? Otherwise I'll do my best but I'm a bit busy these days

**Comment by vhf** [comment]
Published: remark-lint-alphabetize-lists@3.0.0
